import type { Metadata } from 'next';
import { Gloock, Kalnia } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const gloockSerif = Gloock({
  variable: '--font-gloock-serif',
  subsets: ['latin'],
  weight: '400',
});

const kalniaSerif = Kalnia({
  variable: '--font-kalnia-serif',
  weight: ['200', '400', '700'],
});

const gowooonSerif = localFont({
  src: [
    {
      path: '../public/fonts/GowunBatang-Regular.ttf',
      weight: '400',
    },
    {
      path: '../public/fonts/GowunBatang-Bold.ttf',
      weight: '700',
    },
  ],
  variable: '--font-gowoon-serif',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gowooonSerif.variable} ${gloockSerif.variable} ${kalniaSerif.variable} antialiased grid place-items-center`}
      >
        {children}
        <Background />
      </body>
    </html>
  );
}
